import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import App from './App'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout() {
  return (
    <html lang="en">
      <body className={inter.className}>
        <App />
      </body>
    </html>
  )
}